@startuml 'https://plantuml.com/class-diagram'
class Client {
   -name: string
   - account: SavingsAccount
   + getAccount(): SavingsAccount
   + getName(): string
}

class SavingsAccount {
    -accountNumber: string
    -balance: double
    + transfer(amount: double, destinationClient: SavingsAccount): void
    +getBalance(): double
}

Client -> SavingsAccount: + accounts

@enduml